#!/usr/bin/python3
import sys
import os
import markdown

def main(args=None):
    if (args is None or len(args) < 2):
        print("Error, input file missing, usage:")
        print("  markdown-pygments.py <markdown formatted file>")
        return

    markdownInFile = os.path.abspath(args[1])

    (dir, file) = os.path.split(markdownInFile)
    (file, ext) = os.path.splitext(file)
    markdownOutFile = os.path.join(dir, ".".join([file,'html']))

    print("Reading {} and writing to {}".format(markdownInFile,
                                                 markdownOutFile))
    with open(markdownInFile, 'r', encoding='utf-8') as f: text = f.read()
    text = text.replace('\\', '\\\\')
    htm = markdown.markdown(text, extensions=['markdown.extensions.toc',
                                              'markdown.extensions.tables',
                                              'markdown.extensions.extra'])
    with open('skeleton.htm', 'r') as f: html = f.read()
    html = html.replace('CONTENT', htm)
    with open(markdownOutFile, 'w', encoding="utf-8",
        errors="xmlcharrefreplace") as f: f.write(html)

    #os.system('xsel --clipboard < {}'.format(markdownOutFile))
    #print("HTML file is copied to clipboard")

if __name__ == '__main__':
        main(sys.argv)
